import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { XFilesConsole } from '../XFilesConsole';

/**
 * XFilesConsole Tests
 * Generated by Developer Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article III: Schema-Defined Validation
 * - E2E Playwright test requirements
 */

describe('XFilesConsole', () => {
  test('renders component successfully', () => {
    render(<XFilesConsole />);
    expect(screen.getByRole('button')).toBeInTheDocument();
  });

  test('handles user interactions', () => {
    const mockOnAction = jest.fn();
    render(<XFilesConsole onAction={mockOnAction} />);
    
    const button = screen.getByRole('button');
    fireEvent.click(button);
    
    expect(mockOnAction).toHaveBeenCalledWith('click');
  });

  test('displays X-FILES trigger icon', () => {
    render(<XFilesConsole />);
    const xFilesButton = screen.getByLabelText('X-FILES Console');
    expect(xFilesButton).toBeInTheDocument();
  });

  test('maintains constitutional compliance', () => {
    render(<XFilesConsole />);
    const componentElement = screen.getByTestId('comp-1760463275055-6qaeg7ns2');
    expect(componentElement).toHaveAttribute('data-constitution', 'v3.0');
    expect(componentElement).toHaveAttribute('data-x-files', 'enabled');
  });

  test('supports mobile-first design', () => {
    render(<XFilesConsole />);
    // Mobile layout should be visible by default
    const mobileLayout = screen.getByTestId('mobile-layout');
    expect(mobileLayout).toBeInTheDocument();
  });
});
