import { test, expect } from '@playwright/test';

/**
 * UserAuthentication X-FILES Integration Test
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article VI: X-FILES System
 * - Article VII: Case File Management
 * - Article VIII: Observability
 */

test.describe('UserAuthentication X-FILES Integration', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/test/userauthentication');
  });

  test('should display X-FILES trigger icon', async ({ page }) => {
    // Verify X-FILES trigger icon is present
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await expect(xFilesButton).toBeVisible();
    
    // Verify positioning (bottom-right)
    const buttonBox = await xFilesButton.boundingBox();
    expect(buttonBox).toBeTruthy();
  });

  test('should open X-FILES console when triggered', async ({ page }) => {
    // Click X-FILES trigger
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Verify X-FILES console opens
    const console = page.locator('text=X-FILES Console - In-Situ Triage & Action');
    await expect(console).toBeVisible();
  });

  test('should create case files successfully', async ({ page }) => {
    // Open X-FILES console
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Switch to create tab
    await page.click('text=Create Case');
    
    // Fill case file form
    await page.selectOption('select', 'BugReport');
    await page.fill('input[placeholder*="Brief description"]', 'Test bug report');
    await page.fill('textarea', 'This is a test bug report created by automated testing.');
    
    // Submit case file
    await page.click('button:has-text("Create Case File")');
    
    // Verify case file was created
    await page.click('text=Case Files');
    await expect(page.locator('text=Test bug report')).toBeVisible();
  });

  test('should handle case file lifecycle', async ({ page }) => {
    // Open X-FILES console
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Verify case files are displayed
    const caseFiles = page.locator('[data-testid="case-file"]');
    const count = await caseFiles.count();
    
    if (count > 0) {
      // Test case file interaction
      await caseFiles.first().click();
      await expect(page.locator('text=View Details')).toBeVisible();
    }
  });

  test('should maintain constitutional compliance in X-FILES', async ({ page }) => {
    // Open X-FILES console
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Verify constitutional compliance indicators
    const console = page.locator('text=X-FILES Console - In-Situ Triage & Action');
    await expect(console).toBeVisible();
    
    // Verify case types are constitutional
    await page.click('text=Create Case');
    const caseTypes = page.locator('select option');
    await expect(caseTypes).toContainText(['BugReport', 'FeatureRequest', 'SystemAnomaly']);
  });
});
