import { test, expect } from '@playwright/test';

/**
 * UserAuthentication Mobile Responsiveness Test
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article IV: Technical & Architectural Mandates
 * - Mobile-first design (MANDATORY)
 */

test.describe('UserAuthentication Mobile Responsiveness', () => {
  test.beforeEach(async ({ page }) => {
    // Set mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('/test/userauthentication');
  });

  test('should display mobile layout on small screens', async ({ page }) => {
    // Verify mobile-specific elements are visible
    const mobileLayout = page.locator('.block.md\:hidden');
    await expect(mobileLayout).toBeVisible();
    
    // Verify desktop layout is hidden
    const desktopLayout = page.locator('.hidden.md\:block');
    await expect(desktopLayout).not.toBeVisible();
  });

  test('should handle touch interactions', async ({ page }) => {
    // Test touch-friendly interactions
    const button = page.locator('button').first();
    await expect(button).toBeVisible();
    
    // Verify button is touch-friendly (minimum 44px)
    const buttonBox = await button.boundingBox();
    expect(buttonBox?.height).toBeGreaterThanOrEqual(44);
    
    // Test touch interaction
    await button.tap();
  });

  test('should maintain X-FILES accessibility on mobile', async ({ page }) => {
    // Verify X-FILES button is accessible on mobile
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await expect(xFilesButton).toBeVisible();
    
    // Verify touch-friendly sizing
    const buttonBox = await xFilesButton.boundingBox();
    expect(buttonBox?.width).toBeGreaterThanOrEqual(44);
    expect(buttonBox?.height).toBeGreaterThanOrEqual(44);
    
    // Test touch interaction
    await xFilesButton.tap();
    
    // Verify console opens on mobile
    const console = page.locator('text=X-FILES Console - In-Situ Triage & Action');
    await expect(console).toBeVisible();
  });

  test('should handle orientation changes', async ({ page }) => {
    // Test landscape orientation
    await page.setViewportSize({ width: 667, height: 375 });
    
    // Verify component still functions
    const component = page.locator('[data-component-id="comp-1760463275049-v0i5armmt"]');
    await expect(component).toBeVisible();
    
    // Test portrait orientation
    await page.setViewportSize({ width: 375, height: 667 });
    await expect(component).toBeVisible();
  });

  test('should maintain performance on mobile', async ({ page }) => {
    // Measure performance metrics
    const startTime = Date.now();
    
    // Perform interactions
    const button = page.locator('button').first();
    await button.click();
    
    const endTime = Date.now();
    const responseTime = endTime - startTime;
    
    // Verify response time is acceptable (< 100ms)
    expect(responseTime).toBeLessThan(100);
  });
});
