#!/usr/bin/env node

/**
 * Test Runner Script
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article III: Schema-Defined Validation
 * - Live deployment verification
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

async function runTests() {
  console.log('🧪 Running E2E tests under Project Phoenix Constitution v3.0');
  
  try {
    // Run Playwright tests
    console.log('📋 Executing Playwright test suite...');
    execSync('npx playwright test', { 
      stdio: 'inherit',
      cwd: process.cwd()
    });
    
    // Generate test report
    console.log('📊 Generating test report...');
    execSync('npx playwright show-report', { 
      stdio: 'inherit',
      cwd: process.cwd()
    });
    
    // Capture screenshots for visual proof
    console.log('📸 Capturing visual proof...');
    const screenshotsDir = path.join(process.cwd(), 'test-results', 'screenshots');
    if (fs.existsSync(screenshotsDir)) {
      const screenshots = fs.readdirSync(screenshotsDir);
      console.log(`✅ Captured ${screenshots.length} screenshots for visual proof`);
    }
    
    console.log('✅ E2E tests completed successfully');
    console.log('⚖️ Constitutional compliance verified');
    console.log('🔍 X-FILES system integration validated');
    
  } catch (error) {
    console.error('❌ E2E tests failed:', error.message);
    
    // Create X-FILES CaseFile for test failure
    const caseFile = {
      id: `test-failure-${Date.now()}`,
      type: 'SystemAnomaly',
      status: 'Open',
      title: 'E2E Test Suite Failure',
      description: `E2E test execution failed: ${error.message}`,
      timestamp: new Date().toISOString(),
      dossier: {
        userIntent: 'E2E test validation',
        componentId: 'tester-agent',
        componentConfig: {},
        applicationState: { error: error.message },
        logs: [error.stack],
        environment: {
          nodeVersion: process.version,
          platform: process.platform,
          testSuite: 'test-suite-1760463275074'
        }
      }
    };
    
    // Save case file
    const caseFilePath = path.join(process.cwd(), 'test-results', `casefile-${caseFile.id}.json`);
    fs.writeFileSync(caseFilePath, JSON.stringify(caseFile, null, 2));
    
    console.log(`📋 X-FILES CaseFile created: ${caseFile.id}`);
    process.exit(1);
  }
}

// Run tests if called directly
if (require.main === module) {
  runTests();
}

module.exports = { runTests };
