/**
 * Tester Agent - E2E Testing & Validation
 * Project Phoenix Constitution v3.0 (X-FILES Edition)
 * 
 * Testing, validation, and quality assurance
 * Implements Playwright E2E tests from agentDirectives.requiredTests
 */

import { readFile, writeFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';

class TesterAgent {
  constructor() {
    this.tests = [];
    this.testResults = [];
    this.agentDirectives = {
      constitutionRef: '.cursor/rules/pow3r.v3.law.md#article-iii',
      requiredTests: [
        {
          description: 'Verify that Tester Agent can implement E2E tests from agentDirectives.requiredTests',
          testType: 'e2e-playwright',
          expectedOutcome: 'E2E tests implemented successfully with constitutional compliance'
        },
        {
          description: 'Verify that Tester Agent can validate code against schema requirements',
          testType: 'e2e-playwright',
          expectedOutcome: 'Code validation completed with schema compliance verification'
        }
      ],
      selfHealing: {
        enabled: true,
        monitoredMetrics: ['testCoverage', 'testSuccess', 'validationAccuracy'],
        failureCondition: 'testSuccess < 0.95 for 3m',
        repairPrompt: 'Tester Agent has failed to maintain test quality. Analyze test failures, check schema requirements, and repair testing mechanisms according to Article III requirements.'
      }
    };
  }

  /**
   * Initialize Tester Agent
   */
  async initialize() {
    try {
      console.log('🧪 Tester Agent initialized');
      return true;
    } catch (error) {
      console.error('❌ Tester Agent initialization failed:', error);
      return false;
    }
  }

  /**
   * Generate E2E tests from implementation
   * @param {Object} implementation - Implementation from Developer Agent
   * @returns {Object} Test generation result
   */
  async generateTests(implementation) {
    try {
      console.log('🧪 Generating E2E tests for implementation:', implementation.id);

      const testSuite = {
        id: `test-suite-${Date.now()}`,
        implementationId: implementation.id,
        timestamp: new Date().toISOString(),
        status: 'generating',
        tests: [],
        playwrightConfig: null,
        screenshots: [],
        constitutionalCompliance: true
      };

      // Generate tests for each component
      for (const component of implementation.components) {
        const componentTests = await this.generateComponentTests(component, implementation);
        testSuite.tests.push(...componentTests);
      }

      // Generate Playwright configuration
      testSuite.playwrightConfig = await this.generatePlaywrightConfig(testSuite);

      // Generate test runner script
      const testRunner = await this.generateTestRunner(testSuite);

      testSuite.status = 'completed';
      testSuite.completedAt = new Date().toISOString();

      await this.saveTestSuite(testSuite);
      console.log('✅ E2E test generation completed:', testSuite.id);

      return testSuite;

    } catch (error) {
      console.error('❌ E2E test generation failed:', error);
      throw error;
    }
  }

  /**
   * Generate tests for a component
   */
  async generateComponentTests(component, implementation) {
    const tests = [];

    // Generate basic functionality test
    const basicTest = await this.generateBasicTest(component);
    tests.push(basicTest);

    // Generate X-FILES integration test
    const xFilesTest = await this.generateXFilesTest(component);
    tests.push(xFilesTest);

    // Generate mobile responsiveness test
    const mobileTest = await this.generateMobileTest(component);
    tests.push(mobileTest);

    // Generate constitutional compliance test
    const complianceTest = await this.generateComplianceTest(component);
    tests.push(complianceTest);

    return tests;
  }

  /**
   * Generate basic functionality test
   */
  async generateBasicTest(component) {
    const testName = `${component.name}.basic.spec.ts`;
    const testPath = join(process.cwd(), '..', 'e2e-tests', testName);

    const testCode = `import { test, expect } from '@playwright/test';

/**
 * ${component.name} Basic Functionality Test
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article III: Schema-Defined Validation
 * - E2E Playwright test requirements
 */

test.describe('${component.name} Basic Functionality', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to component test page
    await page.goto('/test/${component.name.toLowerCase()}');
  });

  test('should render component successfully', async ({ page }) => {
    // Verify component is rendered
    const component = page.locator('[data-component-id="${component.id}"]');
    await expect(component).toBeVisible();
    
    // Verify constitutional compliance attributes
    await expect(component).toHaveAttribute('data-constitution', 'v3.0');
    await expect(component).toHaveAttribute('data-x-files', 'enabled');
  });

  test('should handle user interactions', async ({ page }) => {
    // Test button click functionality
    const button = page.locator('button').first();
    await expect(button).toBeVisible();
    
    // Click button and verify state change
    await button.click();
    
    // Verify interaction was handled (specific to component type)
    if (component.type === 'react-component') {
      await expect(button).toContainText(/Active|Inactive/);
    }
  });

  test('should maintain state consistency', async ({ page }) => {
    // Test state management
    const component = page.locator('[data-component-id="${component.id}"]');
    
    // Perform multiple interactions
    const button = page.locator('button').first();
    await button.click();
    await button.click();
    
    // Verify state is consistent
    await expect(component).toBeVisible();
  });

  test('should handle error states gracefully', async ({ page }) => {
    // Test error handling
    const component = page.locator('[data-component-id="${component.id}"]');
    
    // Simulate error condition (if applicable)
    await page.evaluate(() => {
      window.dispatchEvent(new ErrorEvent('error', { message: 'Test error' }));
    });
    
    // Verify component still functions
    await expect(component).toBeVisible();
  });
});
`;

    // Ensure directory exists
    await mkdir(dirname(testPath), { recursive: true });
    await writeFile(testPath, testCode);

    return {
      id: `test-${component.id}-basic`,
      name: testName,
      type: 'basic-functionality',
      file: testPath,
      componentId: component.id,
      constitutionalCompliance: true
    };
  }

  /**
   * Generate X-FILES integration test
   */
  async generateXFilesTest(component) {
    const testName = `${component.name}.x-files.spec.ts`;
    const testPath = join(process.cwd(), '..', 'e2e-tests', testName);

    const testCode = `import { test, expect } from '@playwright/test';

/**
 * ${component.name} X-FILES Integration Test
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article VI: X-FILES System
 * - Article VII: Case File Management
 * - Article VIII: Observability
 */

test.describe('${component.name} X-FILES Integration', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/test/${component.name.toLowerCase()}');
  });

  test('should display X-FILES trigger icon', async ({ page }) => {
    // Verify X-FILES trigger icon is present
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await expect(xFilesButton).toBeVisible();
    
    // Verify positioning (bottom-right)
    const buttonBox = await xFilesButton.boundingBox();
    expect(buttonBox).toBeTruthy();
  });

  test('should open X-FILES console when triggered', async ({ page }) => {
    // Click X-FILES trigger
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Verify X-FILES console opens
    const console = page.locator('text=X-FILES Console - In-Situ Triage & Action');
    await expect(console).toBeVisible();
  });

  test('should create case files successfully', async ({ page }) => {
    // Open X-FILES console
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Switch to create tab
    await page.click('text=Create Case');
    
    // Fill case file form
    await page.selectOption('select', 'BugReport');
    await page.fill('input[placeholder*="Brief description"]', 'Test bug report');
    await page.fill('textarea', 'This is a test bug report created by automated testing.');
    
    // Submit case file
    await page.click('button:has-text("Create Case File")');
    
    // Verify case file was created
    await page.click('text=Case Files');
    await expect(page.locator('text=Test bug report')).toBeVisible();
  });

  test('should handle case file lifecycle', async ({ page }) => {
    // Open X-FILES console
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Verify case files are displayed
    const caseFiles = page.locator('[data-testid="case-file"]');
    const count = await caseFiles.count();
    
    if (count > 0) {
      // Test case file interaction
      await caseFiles.first().click();
      await expect(page.locator('text=View Details')).toBeVisible();
    }
  });

  test('should maintain constitutional compliance in X-FILES', async ({ page }) => {
    // Open X-FILES console
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await xFilesButton.click();
    
    // Verify constitutional compliance indicators
    const console = page.locator('text=X-FILES Console - In-Situ Triage & Action');
    await expect(console).toBeVisible();
    
    // Verify case types are constitutional
    await page.click('text=Create Case');
    const caseTypes = page.locator('select option');
    await expect(caseTypes).toContainText(['BugReport', 'FeatureRequest', 'SystemAnomaly']);
  });
});
`;

    // Ensure directory exists
    await mkdir(dirname(testPath), { recursive: true });
    await writeFile(testPath, testCode);

    return {
      id: `test-${component.id}-x-files`,
      name: testName,
      type: 'x-files-integration',
      file: testPath,
      componentId: component.id,
      constitutionalCompliance: true
    };
  }

  /**
   * Generate mobile responsiveness test
   */
  async generateMobileTest(component) {
    const testName = `${component.name}.mobile.spec.ts`;
    const testPath = join(process.cwd(), '..', 'e2e-tests', testName);

    const testCode = `import { test, expect } from '@playwright/test';

/**
 * ${component.name} Mobile Responsiveness Test
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article IV: Technical & Architectural Mandates
 * - Mobile-first design (MANDATORY)
 */

test.describe('${component.name} Mobile Responsiveness', () => {
  test.beforeEach(async ({ page }) => {
    // Set mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('/test/${component.name.toLowerCase()}');
  });

  test('should display mobile layout on small screens', async ({ page }) => {
    // Verify mobile-specific elements are visible
    const mobileLayout = page.locator('.block.md\\:hidden');
    await expect(mobileLayout).toBeVisible();
    
    // Verify desktop layout is hidden
    const desktopLayout = page.locator('.hidden.md\\:block');
    await expect(desktopLayout).not.toBeVisible();
  });

  test('should handle touch interactions', async ({ page }) => {
    // Test touch-friendly interactions
    const button = page.locator('button').first();
    await expect(button).toBeVisible();
    
    // Verify button is touch-friendly (minimum 44px)
    const buttonBox = await button.boundingBox();
    expect(buttonBox?.height).toBeGreaterThanOrEqual(44);
    
    // Test touch interaction
    await button.tap();
  });

  test('should maintain X-FILES accessibility on mobile', async ({ page }) => {
    // Verify X-FILES button is accessible on mobile
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await expect(xFilesButton).toBeVisible();
    
    // Verify touch-friendly sizing
    const buttonBox = await xFilesButton.boundingBox();
    expect(buttonBox?.width).toBeGreaterThanOrEqual(44);
    expect(buttonBox?.height).toBeGreaterThanOrEqual(44);
    
    // Test touch interaction
    await xFilesButton.tap();
    
    // Verify console opens on mobile
    const console = page.locator('text=X-FILES Console - In-Situ Triage & Action');
    await expect(console).toBeVisible();
  });

  test('should handle orientation changes', async ({ page }) => {
    // Test landscape orientation
    await page.setViewportSize({ width: 667, height: 375 });
    
    // Verify component still functions
    const component = page.locator('[data-component-id="${component.id}"]');
    await expect(component).toBeVisible();
    
    // Test portrait orientation
    await page.setViewportSize({ width: 375, height: 667 });
    await expect(component).toBeVisible();
  });

  test('should maintain performance on mobile', async ({ page }) => {
    // Measure performance metrics
    const startTime = Date.now();
    
    // Perform interactions
    const button = page.locator('button').first();
    await button.click();
    
    const endTime = Date.now();
    const responseTime = endTime - startTime;
    
    // Verify response time is acceptable (< 100ms)
    expect(responseTime).toBeLessThan(100);
  });
});
`;

    // Ensure directory exists
    await mkdir(dirname(testPath), { recursive: true });
    await writeFile(testPath, testCode);

    return {
      id: `test-${component.id}-mobile`,
      name: testName,
      type: 'mobile-responsiveness',
      file: testPath,
      componentId: component.id,
      constitutionalCompliance: true
    };
  }

  /**
   * Generate constitutional compliance test
   */
  async generateComplianceTest(component) {
    const testName = `${component.name}.compliance.spec.ts`;
    const testPath = join(process.cwd(), '..', 'e2e-tests', testName);

    const testCode = `import { test, expect } from '@playwright/test';

/**
 * ${component.name} Constitutional Compliance Test
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article I: Prime Directive & Core Philosophy
 * - Article II: pow3r.v3.config.json Supremacy
 * - Article IV: Technical & Architectural Mandates
 * - Article VI: X-FILES System
 */

test.describe('${component.name} Constitutional Compliance', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/test/${component.name.toLowerCase()}');
  });

  test('should comply with Article I: Prime Directive', async ({ page }) => {
    // Verify autonomous operation capability
    const component = page.locator('[data-component-id="${component.id}"]');
    await expect(component).toBeVisible();
    
    // Verify Data as Light philosophy (real-time updates)
    await page.evaluate(() => {
      window.dispatchEvent(new CustomEvent('configUpdate', {
        detail: { testUpdate: true }
      }));
    });
    
    // Component should handle update autonomously
    await expect(component).toBeVisible();
  });

  test('should comply with Article II: Schema Supremacy', async ({ page }) => {
    // Verify schema-driven attributes
    const component = page.locator('[data-component-id="${component.id}"]');
    await expect(component).toHaveAttribute('data-constitution', 'v3.0');
    
    // Verify real-time reconfiguration capability
    await page.evaluate(() => {
      window.dispatchEvent(new CustomEvent('configUpdate', {
        detail: { schemaUpdate: true }
      }));
    });
    
    // Component should update without reload
    await expect(component).toBeVisible();
  });

  test('should comply with Article IV: Technical Mandates', async ({ page }) => {
    // Verify mandatory stack compliance
    const component = page.locator('[data-component-id="${component.id}"]');
    await expect(component).toBeVisible();
    
    // Verify mobile-first design
    await page.setViewportSize({ width: 375, height: 667 });
    await expect(component).toBeVisible();
    
    // Verify unbound design (separation of concerns)
    const hasDataAttributes = await component.evaluate(el => 
      el.hasAttribute('data-component-id') && 
      el.hasAttribute('data-constitution')
    );
    expect(hasDataAttributes).toBe(true);
  });

  test('should comply with Article VI: X-FILES System', async ({ page }) => {
    // Verify X-FILES integration
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await expect(xFilesButton).toBeVisible();
    
    // Verify X-FILES trigger functionality
    await xFilesButton.click();
    const console = page.locator('text=X-FILES Console - In-Situ Triage & Action');
    await expect(console).toBeVisible();
    
    // Verify case file creation capability
    await page.click('text=Create Case');
    await expect(page.locator('select')).toBeVisible();
  });

  test('should maintain constitutional compliance under stress', async ({ page }) => {
    // Stress test constitutional compliance
    const component = page.locator('[data-component-id="${component.id}"]');
    
    // Rapid interactions
    for (let i = 0; i < 10; i++) {
      const button = page.locator('button').first();
      await button.click();
      await page.waitForTimeout(10);
    }
    
    // Verify constitutional compliance maintained
    await expect(component).toHaveAttribute('data-constitution', 'v3.0');
    await expect(component).toHaveAttribute('data-x-files', 'enabled');
  });

  test('should handle constitutional violations gracefully', async ({ page }) => {
    // Simulate constitutional violation
    await page.evaluate(() => {
      window.dispatchEvent(new CustomEvent('constitutional-violation', {
        detail: { article: 'IV', violation: 'test' }
      }));
    });
    
    // Component should remain functional
    const component = page.locator('[data-component-id="${component.id}"]');
    await expect(component).toBeVisible();
    
    // X-FILES should be available for reporting
    const xFilesButton = page.locator('[aria-label="X-FILES Console"]');
    await expect(xFilesButton).toBeVisible();
  });
});
`;

    // Ensure directory exists
    await mkdir(dirname(testPath), { recursive: true });
    await writeFile(testPath, testCode);

    return {
      id: `test-${component.id}-compliance`,
      name: testName,
      type: 'constitutional-compliance',
      file: testPath,
      componentId: component.id,
      constitutionalCompliance: true
    };
  }

  /**
   * Generate Playwright configuration
   */
  async generatePlaywrightConfig(testSuite) {
    const configPath = join(process.cwd(), '..', 'playwright.config.js');

    const configCode = `// Playwright Configuration
// Generated by Tester Agent under Project Phoenix Constitution v3.0

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e-tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/results.json' }],
    ['junit', { outputFile: 'test-results/results.xml' }]
  ],
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure'
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] }
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] }
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] }
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] }
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] }
    }
  ],
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI
  }
});
`;

    await writeFile(configPath, configCode);

    return {
      id: `config-${testSuite.id}`,
      name: 'playwright.config.js',
      type: 'playwright-config',
      file: configPath,
      constitutionalCompliance: true
    };
  }

  /**
   * Generate test runner script
   */
  async generateTestRunner(testSuite) {
    const runnerPath = join(process.cwd(), '..', 'scripts', 'run-tests.js');

    const runnerCode = `#!/usr/bin/env node

/**
 * Test Runner Script
 * Generated by Tester Agent under Project Phoenix Constitution v3.0
 * 
 * Constitutional Compliance:
 * - Article III: Schema-Defined Validation
 * - Live deployment verification
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

async function runTests() {
  console.log('🧪 Running E2E tests under Project Phoenix Constitution v3.0');
  
  try {
    // Run Playwright tests
    console.log('📋 Executing Playwright test suite...');
    execSync('npx playwright test', { 
      stdio: 'inherit',
      cwd: process.cwd()
    });
    
    // Generate test report
    console.log('📊 Generating test report...');
    execSync('npx playwright show-report', { 
      stdio: 'inherit',
      cwd: process.cwd()
    });
    
    // Capture screenshots for visual proof
    console.log('📸 Capturing visual proof...');
    const screenshotsDir = path.join(process.cwd(), 'test-results', 'screenshots');
    if (fs.existsSync(screenshotsDir)) {
      const screenshots = fs.readdirSync(screenshotsDir);
      console.log(\`✅ Captured \${screenshots.length} screenshots for visual proof\`);
    }
    
    console.log('✅ E2E tests completed successfully');
    console.log('⚖️ Constitutional compliance verified');
    console.log('🔍 X-FILES system integration validated');
    
  } catch (error) {
    console.error('❌ E2E tests failed:', error.message);
    
    // Create X-FILES CaseFile for test failure
    const caseFile = {
      id: \`test-failure-\${Date.now()}\`,
      type: 'SystemAnomaly',
      status: 'Open',
      title: 'E2E Test Suite Failure',
      description: \`E2E test execution failed: \${error.message}\`,
      timestamp: new Date().toISOString(),
      dossier: {
        userIntent: 'E2E test validation',
        componentId: 'tester-agent',
        componentConfig: {},
        applicationState: { error: error.message },
        logs: [error.stack],
        environment: {
          nodeVersion: process.version,
          platform: process.platform,
          testSuite: '${testSuite.id}'
        }
      }
    };
    
    // Save case file
    const caseFilePath = path.join(process.cwd(), 'test-results', \`casefile-\${caseFile.id}.json\`);
    fs.writeFileSync(caseFilePath, JSON.stringify(caseFile, null, 2));
    
    console.log(\`📋 X-FILES CaseFile created: \${caseFile.id}\`);
    process.exit(1);
  }
}

// Run tests if called directly
if (require.main === module) {
  runTests();
}

module.exports = { runTests };
`;

    // Ensure directory exists
    await mkdir(dirname(runnerPath), { recursive: true });
    await writeFile(runnerPath, runnerCode);

    return {
      id: `runner-${testSuite.id}`,
      name: 'run-tests.js',
      type: 'test-runner',
      file: runnerPath,
      constitutionalCompliance: true
    };
  }

  /**
   * Save test suite
   */
  async saveTestSuite(testSuite) {
    try {
      const suitePath = join(process.cwd(), 'reports', `test-suite-${testSuite.id}.json`);
      await writeFile(suitePath, JSON.stringify(testSuite, null, 2));
      this.tests.push(testSuite);
    } catch (error) {
      console.error('❌ Failed to save test suite:', error);
    }
  }

  /**
   * Get testing report
   */
  getTestingReport() {
    return {
      testerAgent: 'active',
      totalTestSuites: this.tests.length,
      lastTestSuite: this.tests[this.tests.length - 1]?.id || 'none',
      status: 'operational'
    };
  }
}

export default TesterAgent;
